const nodemailer = require('nodemailer');

// Create transporter with Gmail SMTP
const createTransporter = () => {
    // Check if email is configured
    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
        return null;
    }

    return nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS // Gmail App Password (not regular password)
        }
    });
};

/**
 * Send a batch report via email
 * @param {Object} options
 * @param {string} options.to - Recipient email
 * @param {string} options.clientName - Client name for subject
 * @param {string} options.batchTitle - Batch title
 * @param {string} options.managerName - Sender name
 * @param {Buffer} options.pdfBuffer - PDF report buffer
 * @param {string} options.message - Optional custom message
 */
const sendBatchReport = async ({ to, clientName, batchTitle, managerName, pdfBuffer, message }) => {
    const transporter = createTransporter();

    if (!transporter) {
        throw new Error('Email not configured. Add SMTP_USER and SMTP_PASS to .env');
    }

    const subject = `📊 Verification Report: ${batchTitle}${clientName ? ` - ${clientName}` : ''}`;

    const htmlContent = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: linear-gradient(135deg, #0d9488, #0891b2); padding: 30px; text-align: center;">
                <h1 style="color: white; margin: 0; font-size: 24px;">🔒 PromoSecure</h1>
                <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0;">Privacy-First Promotional Verification</p>
            </div>
            
            <div style="padding: 30px; background: #f8fafc;">
                <h2 style="color: #1e293b; margin-top: 0;">Verification Report</h2>
                
                <p style="color: #475569;">Hello,</p>
                
                <p style="color: #475569;">
                    ${managerName} has shared a verification report with you for <strong>${batchTitle}</strong>.
                </p>
                
                ${message ? `
                    <div style="background: white; border-left: 4px solid #0d9488; padding: 15px; margin: 20px 0;">
                        <p style="color: #475569; margin: 0; font-style: italic;">"${message}"</p>
                    </div>
                ` : ''}
                
                <p style="color: #475569;">
                    Please find the detailed PDF report attached to this email. The report includes:
                </p>
                
                <ul style="color: #475569;">
                    <li>Verification summary and statistics</li>
                    <li>AI duplicate detection results</li>
                    <li>Privacy-protected photo documentation</li>
                    <li>Location and timestamp data</li>
                </ul>
                
                <div style="text-align: center; margin: 30px 0;">
                    <p style="color: #64748b; font-size: 14px;">
                        📎 PDF Report Attached
                    </p>
                </div>
            </div>
            
            <div style="background: #1e293b; padding: 20px; text-align: center;">
                <p style="color: #94a3b8; font-size: 12px; margin: 0;">
                    This report was generated by PromoSecure
                </p>
                <p style="color: #64748b; font-size: 11px; margin: 10px 0 0;">
                    All photos have been processed with AI face detection and privacy blurring
                </p>
            </div>
        </div>
    `;

    const filename = `PromoSecure_Report_${batchTitle.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;

    const mailOptions = {
        from: `"PromoSecure Reports" <${process.env.SMTP_USER}>`,
        to,
        subject,
        html: htmlContent,
        attachments: [
            {
                filename,
                content: pdfBuffer,
                contentType: 'application/pdf'
            }
        ]
    };

    const result = await transporter.sendMail(mailOptions);
    return result;
};

/**
 * Check if email is configured
 */
const isEmailConfigured = () => {
    return !!(process.env.SMTP_USER && process.env.SMTP_PASS);
};

module.exports = { sendBatchReport, isEmailConfigured };
